{{- range $i := until (int .Values.validator.replicas) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sui-validator-config-{{ $i }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: sui-validator-config-{{ $i }}
    creationPolicy: Owner
  data:
    - secretKey: validator.yaml
      remoteRef:
        key: {{ $.Values.namespace }}-validator-{{ $i }}
        property: validator.yaml
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: relay-sponsor
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: relay-sponsor
    creationPolicy: Owner
  data:
    - secretKey: private_key_base64
      remoteRef:
        key: {{ .Values.namespace }}-relay-sponsor
        property: private_key_base64
