apiVersion: v1
kind: Service
metadata:
  name: sui-fullnode
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: sui-fullnode
  ports:
    - name: rpc
      port: {{ .Values.fullnode.port_rpc }}
      targetPort: {{ .Values.fullnode.port_rpc }}
      protocol: TCP
